name: codas-hep
channels:
  - nvidia/label/cuda-12.4.1
  - conda-forge
  - defaults
  
dependencies:
  - python=3.10
#  - cuda-toolkit
  - cupy
  - pip
  - zstandard
  - zstd
  - clang-tools
  - fsspec
  - lz4
  - openssh #otherwise ssh is broken due to bug with openssl it seems
  - pip:
      - jupyterlab-deck
      - jupyterlab-mathjax3
      - scipy
      - keras
      - tensorflow 
      - tensorrt
      - torch
      - h5py
      - networkx
      - tensorboard
      - seaborn
      - xgboost
      - torch-geometric
      - torchvision
      - tqdm
      - nvidia-cudnn-cu12
      #- pycuda #seems that this needs to be installed together with numpy

     
variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
  XLA_FLAGS: "'--xla_gpu_cuda_data_dir=$CONDA_PREFIX/'"
