name: hsf-india
channels:
  - defaults
  - nvidia/label/cuda-12.4.1
dependencies:
  - python=3.10
  - libcurand
  - libcurand-dev
  - cuda-minimal-build=12.4
  - cupy
  - pip
  - zstandard
  - zstd
  - clang-tools
  - fsspec
  - lz4
  - cmake #needed to compile Geant examples
  - openssh #otherwise ssh is broken due to bug with openssl it seems
  - pip:
      - jupyterlab-deck
      - jupyterlab-mathjax3
      - pycuda #seems that this needs to be installed together with numpy

     
variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
  XLA_FLAGS: "'--xla_gpu_cuda_data_dir=$CONDA_PREFIX/'"
