name: codas-hep
channels:
#  - nvidia/label/cuda-12.9
  - conda-forge
  - defaults
  
dependencies:
  - python=3.12
  - pip
  - zstandard
  - zstd
  - clang-tools
  - fsspec
  - lz4
  - openssh #otherwise ssh is broken due to bug with openssl it seems
  - pip:
      - h5py
      - jupyterlab-deck
      - jupyterlab-mathjax3
      - keras
      - networkx
      - nvidia-cudnn-cu12
      - scipy
      - seaborn
      - tensorboard
      - tensorflow[and-cuda] 
      - tensorrt
      - torch
      - torch-geometric
      - torchvision
      - tqdm
      - xgboost
      
      
      #- pycuda #seems that this needs to be installed together with numpy

     
variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
  XLA_FLAGS: "'--xla_gpu_cuda_data_dir=$CONDA_PREFIX/'"
